### ISSUE TITLE
关于ikdtree的未经回环修正的历史点删除

### ISSUE THREAD

**Issue by LiuYMUNI** [hku-mars/LTAOM#10]
请问lasermapping里面的ikdtree是否只负责添加feats_down_world还有回环修正过的correctd_cloud_submap_local这些点，不会把之前添加进去的回环修正之前的错误点删除掉，这些错误点指的是从map_incremental里面添加的带有未经回环修正的feats_down_world的点。代码里没有看到KD_FOREST::Delete_Points的调用。

当然不删除也可以理解，毕竟位姿修正之后，错误点就不会被search到，不会影响lio位姿估计，而且pcd存储也是由loop_optimization_node负责。请问这些对于代码的理解正确吗？

**Comment by hongSS0919** [comment]
有没有可能他是重新构建了一个kdtree，将原有的kdtree直接替换？这部分代码我没细看，不确定我猜测的对不对

**Comment by LiuYMUNI** [comment]
应该是没有的，ikdtree要重新构建的话ikdtree_ptr->Build这个指令肯定得用到，但是lasermapping里面只有最开始用到了，都是ikdtree_ptr->Add_Points来改变ikdtree

**Comment by zuhaozou2017** [comment]
> 有没有可能他是重新构建了一个kdtree，将原有的kdtree直接替换？这部分代码我没细看，不确定我猜测的对不对

是的。
