### ISSUE TITLE
About the note at the end of this Readme.

### ISSUE THREAD

**Issue by Parker-Zer0** [hku-mars/LTAOM#11]
I have included both of the following, but still cannot compile them
//To the place between lines 97~99 of ISAM2. h

Void backup()// To line 199 of ISAM2. h

Void recover()// To line 200 of ISAM2. h

Below is the error section
6: 12: error: 'class gtsam:: ISAM2' has no member named 'backup'
826 | isam_ ->backup()// Self defined isam function, you need to compile gtsam with provided note in Readme
|^~~~~~
/Ws-LTAOM/src/LTAOM/loop-optimization/src/loop-optimization node. cpp: 874:16: error: 'class gtsam:: ISAM2' has no member named 'recover'
874 | isam_ ->recover()// Self defined isam function, you need to compile gtsam with provided note in Readme
|^~~~~~~

**Comment by zuhaozou2017** [comment]
I guess you does not link your program with newly complied gtsam libraries. Please remove original ones, compile and cmake install to the place your program can find.
