### ISSUE TITLE
运行环境

### ISSUE THREAD

**Issue by wangyan0825** [hku-mars/LTAOM#13]
您好，我在程序运行到void extract_binary这个函数的时候，内存爆了导致进程死掉。（传入点云数量大概13万个）
报错如下：
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
所以想咨询一下您这边电脑配置是什么样的？还是说这个问题不是由于硬件环境导致的？

**Comment by zuhaozou2017** [comment]
https://onlinelibrary.wiley.com/doi/epdf/10.1002/rob.22337
论文里实验部分有记录。
关于extract_binary传入点云过大，应该是生成二维向量dis_containner 或者binary containner有问题。因为我没有你的环境与数据，我无法确切判断到具体哪里出发问题。如果你的问题还在，请提供一些你自己lc_debug的log,  里面最好在我说的位置打 log 信息。
