### ISSUE TITLE
关于运行程序。

### ISSUE THREAD

**Issue by JiangWeiHn** [hku-mars/LTAOM#19]
我使用的是速腾的激光雷达，fast-lio部分通过修改程序，已经能跑通，但不知道如何设置loop_optimzation中的yaml中的参数，请问loopopt_config_nclt.yaml文件中的LCKPFCOV之类的参数是什么意思？针对速腾的雷达，我该怎么设置？

**Comment by zuhaozou2017** [comment]
LCKPFCOV 是key pt factor的noise值。我建议看看文章协助理解先。然后再看参数所在位置就能理解。代码注释在下一版我会加一部分这些参数的解释（目前有点忙）。

https://onlinelibrary.wiley.com/doi/epdf/10.1002/rob.22337
