### ISSUE TITLE
z轴飞了

### ISSUE THREAD

**Issue by JiangWeiHn** [hku-mars/LTAOM#25]
请问我在采集的较为平整的公园的数据上，建图效果很好，测试的每个点的位置和rtk的坐标对比，经纬度误差都在10cm内。用同样的参数，相同小车采集的公司园区数据，有斜坡，也有一些较窄的长道。跑的结果如下图所示
![2024-08-06 11-40-25 的屏幕截图](https://github.com/user-attachments/assets/64b19d97-71dc-49e3-b1de-189a822035c8)
![2024-08-06 11-41-39 的屏幕截图](https://github.com/user-attachments/assets/ede2517f-d3b1-464f-b184-395a3b113ff6)
z轴明显漂移，有什么建议么？谢谢。

**Comment by woshinidiesb** [comment]
FAST-LIO-Multi-Sensor-Fusion 使用效果和这个对比有什么差异

**Comment by JiangWeiHn** [comment]
gnss有抑制效果，但横向也有漂移。现在正尝试把他们结合起来。

**Comment by woshinidiesb** [comment]
First at all,thank you very much for your reply.l found a few method about how to&nbsp; combine gnss to fast_lio at last week.lt's named that FAST_LIO_SAM(https://github.com/kahowang/FAST_LIO_SAM)  and FAST-LIO-Multi-Sensor-Fusion(https://github.com/zhh2005757/FAST-LIO-Multi-Sensor-Fusion) .the fast_lio_samcombine gnss to fast_lio in gtsam .however, the FAST-LIO-Multi-Sensor-Fusion that even use the odometry to constraint pose combine gnss to fast_lio in ieskf , but the both code is in ros1,however,l can't transform it to ros2 and use it.May be the both code can give you some idea


★往事“曾经
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hku-mars/LTAOM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月26日(星期一) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hku-mars/LTAOM] z轴飞了 (Issue #25)





 
gnss有抑制效果，但横向也有漂移。现在正尝试把他们结合起来。

**Comment by zuhaozou2017** [comment]
抱歉很晚回复你，估计你都fix问题了。较窄的长道是LIO work的不太好的case，正常是会漂移的，因为在一个自由度上是欠约束的。这个我这个算法没有什么特别的处理。虽然无法帮你解决问题，但你可以参考最近TRO的一个抗退化的工作，叫做XICP (https://arxiv.org/abs/2211.16335)。

**Comment by JiangWeiHn** [comment]
感谢您的回复，目前还没有解决，您的回复很有用。
