### ISSUE TITLE
调参说明

### ISSUE THREAD

**Issue by WangShiJieAOTM** [hku-mars/LTAOM#30]
作者您好，想请问一下是否有调参说明，在室内场景中测试，First Session 建图质量不如直接使用FAST-LIO2，是loop_optimization的相关参数设置的问题吗

**Comment by zuhaozou2017** [comment]
您好, 感谢你的反馈。“First Session 建图质量不如直接使用FAST-LIO2”， 关于这部分陈述，您能否提供一些图片证明，我想看看。因为套代码里的fastlio2版本是落后于开源版的，徐威师兄给我的这个版本是有点早的，后期他肯定得到其他反馈更新了代码，但我这边手动merge新的更新其实是非常耗时的，所以我想看看差距有多大，是否值得手动merge一版。
“是loop_optimization的相关参数设置的问题吗”，我的建议在rviz里把lio的结果开启可视化，闭环的结果也可视化，先确定是否闭环比lio的建图结果更差。

**Comment by WangShiJieAOTM** [comment]
> 您好, 感谢你的反馈。“First Session 建图质量不如直接使用FAST-LIO2”， 关于这部分陈述，您能否提供一些图片证明，我想看看。因为套代码里的fastlio2版本是落后于开源版的，徐威师兄给我的这个版本是有点早的，后期他肯定得到其他反馈更新了代码，但我这边手动merge新的更新其实是非常耗时的，所以我想看看差距有多大，是否值得手动merge一版。 “是loop_optimization的相关参数设置的问题吗”，我的建议在rviz里把lio的结果开启可视化，闭环的结果也可视化，先确定是否闭环比lio的建图结果更差。

感谢你的回复，已经找到建图质量差的原因，我使用Pandar-XT32雷达，点云数据结构与Pandar128不同，导致了建图的错误。
```
namespace pandar128_ros {
struct EIGEN_ALIGN16 Point {
  PCL_ADD_POINT4D;
  float timestamp;
  uint16_t  ring;
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};
}

POINT_CLOUD_REGISTER_POINT_STRUCT(pandar128_ros::Point,
                                  (float, x, x)
                                  (float, y, y)
                                  (float, z, z)
                                  (float, timestamp, timestamp)
                                  (std::uint16_t, ring, ring)
)
```
改成
```
namespace pandar_ros {
    struct EIGEN_ALIGN16 Point {
        PCL_ADD_POINT4D;
        float intensity;
        double timestamp;
        uint16_t  ring;
        EIGEN_MAKE_ALIGNED_OPERATOR_NEW
    };
}
POINT_CLOUD_REGISTER_POINT_STRUCT(pandar_ros::Point,
                                  (float, x, x)
                                          (float, y, y)
                                          (float, z, z)
                                          (float, intensity, intensity)
                                          (double, timestamp, timestamp)
                                          (std::uint16_t, ring, ring)
)
```
hku-mars/FAST_LIO#141
