### ISSUE TITLE
can not open yaml file

### ISSUE THREAD

**Issue by wolf943134497** [hku-mars/LTAOM#5]
Failed to open settings file at: /home/LTAOM_ws/src/LTAOM/STD/config/config_velo_nclt.yaml
may be the yaml format is invaild?

**Comment by hongSS0919** [comment]
I can run it now. I guess it's a problem with your path.
/home**//**LTAOM_ws/src/LTAOM/STD/config/config_velo_nclt.yaml

**Comment by wolf943134497** [comment]
@hongSS0919  Thanks for your help
my path is /home/LTAOM_ws/src/LTAOM/STD/config/config_velo_nclt.yaml, looks ok
my env is  ubuntu20.04, ros noetic, opencv 3.4.3
can you tell me your env version?  Thanks

**Comment by wolf943134497** [comment]
@hongSS0919  Have you tested Multisession map stitching?  Thanks!

**Comment by hongSS0919** [comment]
I don't know either, I only tested it on  Riverside01
