### ISSUE TITLE
关于loop_optimization 

### ISSUE THREAD

**Issue by JiangWeiHn** [hku-mars/LTAOM#6]
请问我能不能单独使用loop_optimization 模块到lio-sam中？能详细说一下这个模块的输入和输出么？

**Comment by zuhaozou2017** [comment]
我的保守答案是可以结合过去，但是我没试过。 建议你需要先理解代码，因为loop optimization需要到std-loop detection提取的key points, 还涉及到代码里一些写死key point factors的参数。 你可以尝试关到key point factors 相关的东西，在cpp最上面应该有个#define 什么robust estimator，你把他开启应该(时间久了，不太确定)就关掉key point factors。关掉情况下，输入：1. 回环算法给与的6dof icp transformation 以及 检测到的回环帧key frame id，2. 回环算法划分的当前帧key frame 信息：key frame id, key frame cloud, key frame pose. 输出：闭环关键帧轨迹，闭环地图。

**Comment by JiangWeiHn** [comment]
谢谢，我看看论文和程序
