### ISSUE TITLE
Multi-session mode question

### ISSUE THREAD

**Issue by wolf943134497** [hku-mars/LTAOM#7]
@zuhaozou2017   Thanks for your great works!
I have a question about the multi session mode:

If the two dataset only have some overlap at the middle moment, there is no overlapping area at other times. Is LTAOM suitable for this scenario? and merge 2 maps into one large map containing all areas. Thanks!

**Comment by zuhaozou2017** [comment]
I think the answer is "yes".  LTAOM will automatically do relocalization once it enters the overlapping area.

**Comment by wolf943134497** [comment]
@zuhaozou2017 Thanks for your rapid reply!  
LTAOM will automatically do relocalization once it enters the overlapping area,  so if I want to merge 2 maps into one large map containing all areas, the prior submap pose must be global pose or LTAOM estimate  two path coordinate transformation, otherwise the second path will discard the map before encountering the overlapping area. 
Is my understanding correct? Thanks！

**Comment by zuhaozou2017** [comment]
global pose means last session's keyframe poses. Of course, you can do some gps fusion coding.

"otherwise the second path will discard the map before encountering the overlapping area" - No, two sessions' maps will just be what they like in the single session mode, i.e., not consistent overlapping.

**Comment by wolf943134497** [comment]
> global pose means last session's keyframe poses. Of course, you can do some gps fusion coding.
> 
> "otherwise the second path will discard the map before encountering the overlapping area" - No, two sessions' maps will just be what they like in the single session mode, i.e., not consistent overlapping.

It means the multisession map is inconsistent in overlapping areas? the map diff depending on each session pose accuracy.  
Another great job from your team HBA can solve the not consistent overlapping map problem?  Thanks

**Comment by wolf943134497** [comment]
> "It means the multisession map is inconsistent in overlapping areas? the map diff depending on each session pose accuracy. when LTAOM do relocalization in the overlapping area, the second session will not do mapping and the coordinate of the second session map will convert to first session map？" - totally opposite, multisession map is consistent in overlapping areas. relocalization will make coordinate 2 -> 1.
> 
> "Another great job from your team HBA can solve the not consistent overlapping map problem? Thanks" - yes

Thanks for  your patient answer and great paper&codes. Thanks

**Comment by wolf943134497** [comment]
@zuhaozou2017  Sorry to bother you again,  If I have more than two data to merge like 3-4, The output of LTAOM is 3-4 map and keyframe pose like in single session mode，all the map and pose in the first data Coordinate? Thanks
